# Generated by Django 2.0.2 on 2018-10-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50, verbose_name='School name')),
                ('school_email', models.EmailField(max_length=50, verbose_name='School email')),
                ('school_mobile_no', models.IntegerField(null=True, verbose_name='School mobile no')),
                ('school_address', models.CharField(max_length=50, verbose_name='School address')),
                ('cid', models.CharField(max_length=50, verbose_name='CID')),
                ('user_type', models.CharField(choices=[('school', 'school'), ('authorised_person', 'Authorised Person'), ('owner_chairman', 'Owner/Chairman'), ('principal', 'Principal')], max_length=50, verbose_name='User type')),
                ('mobile_confirm', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'School registration',
                'verbose_name_plural': 'school registration',
            },
        ),
    ]
