# Generated by Django 2.0.2 on 2018-10-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationschool',
            name='school_mobile_no',
            field=models.CharField(max_length=10, null=True, verbose_name='School mobile no'),
        ),
    ]
