# Generated by Django 2.0.2 on 2018-10-23 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration_school', '0001_initial'),
        ('chapter', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50, verbose_name='Teacher name')),
                ('teacher_email', models.EmailField(max_length=50, verbose_name='Teacher email')),
                ('teacher_mobile_no', models.IntegerField(verbose_name='Teacher mobile no')),
                ('teacher_token', models.CharField(max_length=50, verbose_name='Token')),
                ('email_confirm', models.BooleanField(default=False)),
                ('mobile_confirm', models.BooleanField(default=False)),
                ('classes', models.ManyToManyField(to='chapter.classes')),
                ('school_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_school.RegistrationSchool')),
                ('teacher_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapter.Subject')),
            ],
            options={
                'verbose_name': 'Teacher registration',
                'verbose_name_plural': 'Teacher registration',
            },
        ),
    ]
