# Generated by Django 2.0.2 on 2018-10-23 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0002_questionbank'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrainStorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brain_storm_image_field', models.ImageField(upload_to='brainstorm')),
                ('chapter_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapter.Chapter')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapter.classes')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapter.Subject')),
            ],
            options={
                'verbose_name': 'Brain Storm',
                'verbose_name_plural': 'Brain Storms',
            },
        ),
    ]
