# Generated by Django 2.0.2 on 2018-10-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0003_brainstorm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brainstorm',
            name='brain_storm_image_field',
            field=models.FileField(upload_to='brainstorm'),
        ),
    ]
