# Generated by Django 2.0.2 on 2018-10-23 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0004_auto_20181023_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_field', models.FileField(upload_to='word_search')),
                ('chapter_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapter.Chapter')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapter.classes')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapter.Subject')),
            ],
            options={
                'verbose_name': 'Word search',
                'verbose_name_plural': 'Word search',
            },
        ),
        migrations.RemoveField(
            model_name='brainstorm',
            name='chapter_no',
        ),
        migrations.RemoveField(
            model_name='brainstorm',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='brainstorm',
            name='subject',
        ),
        migrations.DeleteModel(
            name='BrainStorm',
        ),
    ]
