# Generated by Django 2.0.2 on 2018-10-23 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0005_auto_20181023_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrainStorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brain_storm', models.TextField(verbose_name='Brain Storm')),
                ('chapter_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapter.Chapter')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapter.classes')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapter.Subject')),
            ],
            options={
                'verbose_name': 'Brain Storm',
                'verbose_name_plural': 'Brain Storms',
            },
        ),
        migrations.CreateModel(
            name='FindOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('find_out', models.TextField(verbose_name='Find Out')),
                ('chapter_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapter.Chapter')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapter.classes')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapter.Subject')),
            ],
            options={
                'verbose_name': 'Find Out',
                'verbose_name_plural': 'Find Outs',
            },
        ),
        migrations.CreateModel(
            name='TellYourTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tell_your_teacher', models.TextField(verbose_name='Tell your teacher')),
                ('chapter_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapter.Chapter')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapter.classes')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapter.Subject')),
            ],
            options={
                'verbose_name': 'Tell your teacher',
                'verbose_name_plural': 'Tell your teachers',
            },
        ),
    ]
