# Generated by Django 2.0.2 on 2018-10-23 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0007_auto_20181023_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tellyourteacher',
            options={'verbose_name': 'Tell Your Teacher', 'verbose_name_plural': 'Tell Your Teachers'},
        ),
        migrations.AlterModelOptions(
            name='unitwithchapters',
            options={'verbose_name': 'Chapter With Unit', 'verbose_name_plural': 'Chapter With Unit'},
        ),
        migrations.AlterModelOptions(
            name='wordsearch',
            options={'verbose_name': 'Word Search', 'verbose_name_plural': 'Word Search'},
        ),
        migrations.AddField(
            model_name='questionbank',
            name='category',
            field=models.CharField(choices=[(0, 'Intext'), (1, 'Textbook Exercise')], default=django.utils.timezone.now, max_length=50, verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionbank',
            name='question_type',
            field=models.CharField(choices=[(0, 'Oral Questions'), (1, 'Name of the following ')], default=django.utils.timezone.now, max_length=50, verbose_name='Question Type'),
            preserve_default=False,
        ),
    ]
