# Generated by Django 2.0.2 on 2018-10-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0008_auto_20181023_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='category',
            field=models.CharField(choices=[(1, 'Intext'), (2, 'Textbook Exercise')], max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='question_type',
            field=models.CharField(choices=[(1, 'Oral Questions'), (2, 'Name of the following ')], max_length=50, verbose_name='Question Type'),
        ),
    ]
